name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies from requirements.txt
          pip install pytest  # Explicitly install pytest to ensure it's available

      - name: Check pytest version (debugging)
        run: |
          pytest --version  # Check if pytest is installed and available

      - name: Run tests
        run: |
          pytest  # Run your tests using pytest

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Build Docker image (optional)
        run: |
          docker build -t my-flask-app .  # Build Docker image

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to your chosen platform (AWS, Azure, etc.)
        run: |
          echo "Deploying to cloud platform"
